"""
Forensic export -- produce a single, self-contained JSON (or JSON.gz)
artifact for ONE run_id, suitable for uploading directly to an AI system
(Claude, Copilot, or a future forensic tool) for incident investigation --
see docs/architecture.md "Forensic Export".

Usage:
    python scripts/export_run.py RACK01-00000001
    python scripts/export_run.py RACK01-00000001 --summary-only
    python scripts/export_run.py RACK01-00000001 --include-measurements --include-raw-hardware-log
    python scripts/export_run.py RACK01-00000001 --gzip
    python scripts/export_run.py RACK01-00000001 --output /path/to/file.json

Design principles (see docs/architecture.md for the full review this
implements):

  - Read-only, zero side effects: uses DataStorage.open_for_forensic_
    export() -- never allocates a run_sequence value, never creates
    schema, never creates a CSV directory, never mutates either database.
  - Locates telemetry ONLY via the stored run_summary.telemetry_db column
    -- never inferred from a timestamp, never guessed.
  - `incident_summary`/`safety`/`forensic_findings` are 100% deterministic
    rollups of stored data -- nothing here is AI-generated or a heuristic
    guess. `narrative` is a template-filled sentence, not free text.
  - Telemetry-unavailable is never silently treated as "no faults" -- see
    _unavailable_safety_section() below: fault counts become None
    (unknown), never 0 (confirmed clean), whenever the source data
    (event_log, which lives in the telemetry database) could not be read.
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config.settings import Settings
from data.storage import DataStorage
from utils.event_format import EventType, parse_event_fields
from utils.safety_fault import (
    FORENSIC_FINDINGS_BY_VERIFICATION_RESULT, parse_safety_fault_event, verification_result_meaning,
)

EXPORT_VERSION = "1.0"
DEFAULT_GZIP_THRESHOLD_BYTES = 10 * 1024 * 1024  # 10 MB -- see write_export()'s docstring

DESCRIPTION = (
    "This is a self-contained forensic export of one battery-test run, generated by "
    "scripts/export_run.py for AI-assisted incident investigation. Read 'incident_summary' "
    "first for an instant digest of what happened; 'timeline' gives full merged chronology "
    "(event_log + execution_state, already sorted -- no need to reconstruct it from separate "
    "tables); 'safety' and 'forensic_findings' give correlated safety-fault detail (raised/"
    "acknowledged pairs already joined by fault_id); 'critical_events' is a filtered view of "
    "'timeline' containing only safety/error-severity entries. 'run_summary', "
    "'execution_state', 'event_log', 'measurements', and 'raw_hardware_log' are the "
    "underlying raw records everything above is derived from. Every field in "
    "'incident_summary'/'safety'/'forensic_findings' is a deterministic lookup from stored "
    "data, computed by Python code -- none of it is AI-generated, inferred, or scored."
)

ROOT_CAUSE_CAVEAT = (
    "verification_result describes the failure mode observed (what the SMU readback "
    "reported), not a diagnosis of the underlying physical cause -- STILL_ENABLED means the "
    "output was electrically confirmed on, not why the disable command failed to take "
    "effect (a driver fault, a stuck relay, and a firmware hang would all look identical "
    "from this field alone)."
)

# Timeline severity for a station_state transition -- event_log rows
# already carry a real `level` column; station_state does not, so this is
# the one small curated mapping needed to give station_state entries a
# comparable severity for the critical_events filter.
_STATE_SEVERITY = {
    "STATION_FAULT": "CRITICAL",
    "SAFETY_VIOLATION": "CRITICAL",
    "FAILED": "ERROR",
    "CANCELLED": "WARNING",
}

# Always promoted into critical_events regardless of event_log.level --
# see docs/architecture.md "Forensic Export"/"Critical Events": some of
# these (SAFETY_FAULT_ACKNOWLEDGED) are correctly logged at level=INFO
# (an acknowledgement is a resolution, not a problem) but are still one of
# the golden forensic questions ("did the operator acknowledge?") and must
# never be filtered out by a bare level check.
ALWAYS_CRITICAL_EVENT_TYPES = frozenset({
    EventType.SAFETY_FAULT_RAISED,
    EventType.SAFETY_FAULT_ACKNOWLEDGED,
    EventType.GROUP_RUN_ABORTED_STATION_FAULT,
    EventType.SAFETY_MONITOR_TRIGGERED,
})


class ExportError(Exception):
    """Raised when run_id itself cannot be found -- nothing to export."""


# -----------------------------------------------------------------------
# Section builders -- each is a pure function over already-fetched rows,
# so they're independently unit-testable without a database.
# -----------------------------------------------------------------------

def _build_timeline(event_rows: list, station_state_rows: list) -> list:
    """
    Merge event_log + station_state into one chronologically-sorted list
    -- see docs/architecture.md "Timeline". Deliberately excludes
    raw_hardware_log (too high-volume, and safety-relevant rows there are
    already represented via event_log's SAFETY_FAULT_RAISED entries).
    """
    entries = []
    for row in event_rows:
        parsed = parse_event_fields(row["message"])
        entries.append({
            "timestamp": row["timestamp"],
            "source": "event_log",
            "event": parsed.get("event_type", "LOG_MESSAGE"),
            "detail": row["message"],
            "severity": row.get("level") or "INFO",
        })
    for row in station_state_rows:
        state = row.get("state")
        detail_bits = [f"{k}={row[k]}" for k in ("channel", "relay") if row.get(k) is not None]
        detail = f"state={state}" + (" " + " ".join(detail_bits) if detail_bits else "")
        entries.append({
            "timestamp": row["timestamp"],
            "source": "station_state",
            "event": state,
            "detail": detail,
            "severity": _STATE_SEVERITY.get(state, "INFO"),
        })
    entries.sort(key=lambda e: e["timestamp"])
    return entries


def _build_critical_events(timeline: list) -> list:
    """
    A filtered VIEW of `timeline`, not an independently-populated list --
    see docs/architecture.md "Critical Events": two lists maintained
    separately is exactly the kind of thing that silently drifts apart.
    """
    return [
        entry for entry in timeline
        if entry["severity"] in ("ERROR", "CRITICAL") or entry["event"] in ALWAYS_CRITICAL_EVENT_TYPES
    ]


def _build_safety_section(event_rows: list) -> dict:
    """
    Dedicated safety section -- joins SAFETY_FAULT_RAISED with its
    SAFETY_FAULT_ACKNOWLEDGED via fault_id, so the AI never has to do
    this correlation itself (see docs/architecture.md "Safety Section").
    """
    raised, acknowledged_at_by_fault_id = [], {}
    for row in event_rows:
        fields = parse_safety_fault_event(row["message"])
        if not fields:
            continue
        if fields["event_type"] == EventType.SAFETY_FAULT_RAISED:
            raised.append({"_row_timestamp": row["timestamp"], **fields})
        elif fields["event_type"] == EventType.SAFETY_FAULT_ACKNOWLEDGED:
            acknowledged_at_by_fault_id[fields.get("acknowledges_fault_id")] = row["timestamp"]

    fault_timeline = []
    for fault in raised:
        fault_id = fault.get("fault_id")
        verification_result = fault.get("verification_result")
        fault_timeline.append({
            "fault_id": fault_id,
            "raised_at": fault["_row_timestamp"],
            "acknowledged_at": acknowledged_at_by_fault_id.get(fault_id),
            "device_name": fault.get("device_name"),
            "device_type": fault.get("device_type"),
            "position": fault.get("position"),
            "context": fault.get("context"),
            "source_method": fault.get("source_method"),
            "reason": fault.get("reason"),
            "verification_result": verification_result,
            "verification_result_meaning": (
                verification_result_meaning(verification_result) if verification_result else None
            ),
        })

    return {
        "available": True,
        "reason": None,
        "fault_count": len(fault_timeline),
        "acknowledged_count": sum(1 for f in fault_timeline if f["acknowledged_at"] is not None),
        "fault_timeline": fault_timeline,
    }


def _unavailable_safety_section(reason: str) -> dict:
    """
    Telemetry unavailable -- see module docstring: fault counts must be
    None (unknown), never 0 (which would falsely read as "confirmed
    clean"). event_log (the safety section's only source) lives in the
    telemetry database, so an unreachable telemetry file means the safety
    section genuinely cannot be assessed, not that nothing happened.
    """
    return {"available": False, "reason": reason, "fault_count": None,
            "acknowledged_count": None, "fault_timeline": []}


def _build_forensic_findings(fault_timeline: list) -> list:
    """
    Deterministic interpretation layer -- see docs/architecture.md
    "Forensic Findings". NO heuristics, NO confidence scoring: every
    value is a fixed lookup (FORENSIC_FINDINGS_BY_VERIFICATION_RESULT)
    keyed only by the stored verification_result string. Cross-referenced
    to the `safety` section by fault_id -- device/position/reason/etc.
    live there, not duplicated here.
    """
    findings = []
    for fault in fault_timeline:
        verification_result = fault.get("verification_result")
        mapping = FORENSIC_FINDINGS_BY_VERIFICATION_RESULT.get(
            verification_result, {"physical_state_confidence": "UNKNOWN", "communication_failure": None},
        )
        findings.append({
            "fault_id": fault["fault_id"],
            "verification_result": verification_result,
            "physical_state_confidence": mapping["physical_state_confidence"],
            "communication_failure": mapping["communication_failure"],
            "operator_acknowledged": fault["acknowledged_at"] is not None,
        })
    return findings


def _testing_continued_after_fault(event_rows: list, primary_fault: dict) -> bool:
    """
    Scoped to THIS run_id only -- see docs/architecture.md "Incident
    Summary": whether a DIFFERENT position in the same Group -> ALL run
    continued afterward is a cross-run question outside what a single
    run's export can answer. Within one run, a fault is normally terminal
    (the raising sequence re-raises immediately after acknowledgement),
    so False is the expected, correct answer in the common case -- this
    field exists to positively CONFIRM that, not to detect an anomaly.
    """
    if primary_fault is None:
        return False
    reference_time = primary_fault.get("acknowledged_at") or primary_fault.get("raised_at")
    if reference_time is None:
        return False
    return any(row["timestamp"] > reference_time for row in event_rows)


def _build_narrative(run: dict, primary_fault, operator_acknowledged, testing_continued,
                      telemetry_available: bool) -> str:
    """Template-filled, deterministic -- see module docstring. Never an
    LLM call; that would reintroduce non-determinism into a forensic
    artifact whose entire value is being reproducible and auditable."""
    if not telemetry_available:
        return (
            f"Run {run.get('run_id')} ({run.get('test_type')}): result={run.get('result')}, "
            f"stop_reason={run.get('stop_reason')}. Safety fault detail unavailable -- "
            f"telemetry database not accessible for this run."
        )
    if primary_fault is None:
        return (
            f"Run {run.get('run_id')} ({run.get('test_type')}) completed with "
            f"result={run.get('result')}, stop_reason={run.get('stop_reason')}."
        )
    verification_result = primary_fault.get("verification_result")
    label = verification_result.upper() if verification_result else "UNKNOWN"
    ack_clause = "Operator acknowledged." if operator_acknowledged else "NOT acknowledged."
    continued_clause = "Testing continued afterward." if testing_continued else "Testing did not continue."
    return f"SAFETY FAULT: Output could not be verified OFF ({label}). {ack_clause} {continued_clause}"


def _build_incident_summary(run: dict, station_state_rows: list, safety_section: dict,
                             event_rows: list, telemetry_available: bool) -> dict:
    """The 30-second digest -- see docs/architecture.md "Incident
    Summary". Every field is a deterministic lookup/derivation from
    already-computed data; nothing here re-queries or re-interprets."""
    final_execution_state = station_state_rows[-1]["state"] if station_state_rows else None

    if not safety_section["available"]:
        fault_count = acknowledged_count = operator_acknowledged = testing_continued = None
        primary = None
    else:
        fault_timeline = safety_section["fault_timeline"]
        fault_count = safety_section["fault_count"]
        acknowledged_count = safety_section["acknowledged_count"]
        operator_acknowledged = acknowledged_count > 0
        primary = fault_timeline[0] if fault_timeline else None
        testing_continued = _testing_continued_after_fault(event_rows, primary) if primary else False

    additional_fault_count = max(0, fault_count - 1) if fault_count is not None else None

    return {
        "run_id": run.get("run_id"),
        "station_id": run.get("station_id"),
        "station_name": run.get("station_name"),
        "result": run.get("result"),
        "stop_reason": run.get("stop_reason"),
        "duration_s": run.get("duration_s"),
        "final_execution_state": final_execution_state,
        "safety_fault_count": fault_count,
        "acknowledged_fault_count": acknowledged_count,
        "operator_acknowledged": operator_acknowledged,
        "testing_continued_after_fault": testing_continued,
        "primary_failure_mode": primary.get("verification_result") if primary else None,
        "primary_device": primary.get("device_name") if primary else None,
        "additional_fault_count": additional_fault_count,
        "root_cause_caveat": ROOT_CAUSE_CAVEAT if primary else None,
        "narrative": _build_narrative(run, primary, operator_acknowledged, testing_continued, telemetry_available),
    }


def _build_event_log_section(event_rows: list) -> list:
    """Every event_log row, plus a `parsed_fields` dict for any row in
    the EVENT_TYPE=... format -- saves the AI from re-parsing KEY=value
    text it has already been handed once, structured, in `safety`."""
    entries = []
    for row in event_rows:
        entry = dict(row)
        parsed = parse_event_fields(row["message"])
        if parsed:
            entry["parsed_fields"] = parsed
        entries.append(entry)
    return entries


def _channel_stats(rows: list, field: str) -> dict:
    values = [row[field] for row in rows if row.get(field) is not None]
    if not values:
        return {}
    return {f"min_{field}": min(values), f"max_{field}": max(values), f"avg_{field}": sum(values) / len(values)}


def _build_measurements_section(rows: list, include_full: bool, telemetry_available: bool, reason: str,
                                 sample_size: int = 10) -> dict:
    """
    Default: row_count + per-channel stats + first/last sample + a
    bounded sample -- ALWAYS present regardless of `include_full`, since
    these are cheap aggregates, not a row dump (see docs/architecture.md
    "Measurements" -- "always include, even when full rows are omitted").
    Full rows only with --include-measurements.
    """
    if not telemetry_available:
        return {"available": False, "reason": reason, "row_count": None}

    row_count = len(rows)
    per_channel: dict = {}
    for row in rows:
        channel_key = str(row.get("channel"))
        per_channel.setdefault(channel_key, []).append(row)
    per_channel_statistics = {
        channel_key: {
            **_channel_stats(channel_rows, "voltage_v"),
            **_channel_stats(channel_rows, "current_a"),
            **_channel_stats(channel_rows, "temp_c"),
        }
        for channel_key, channel_rows in per_channel.items()
    }

    if row_count <= sample_size * 2:
        sample = rows
    else:
        sample = rows[:sample_size] + rows[-sample_size:]

    return {
        "available": True,
        "row_count": row_count,
        "per_channel_statistics": per_channel_statistics,
        "first_sample": rows[0] if rows else None,
        "last_sample": rows[-1] if rows else None,
        "sample": None if include_full else sample,
        "full_rows_included": include_full,
        "rows": rows if include_full else None,
    }


def _decode_json_field(value):
    if not value:
        return value
    try:
        return json.loads(value)
    except (json.JSONDecodeError, TypeError):
        return value  # e.g. a repr() fallback from data/raw_hardware_log.py::_safe_json()


def _build_raw_hardware_log_section(rows: list, include_full: bool, telemetry_available: bool, reason: str) -> dict:
    """
    Default: count + distinct error_types only -- see docs/architecture.md
    "Raw Hardware Log" ("always include, even when not embedded"). Full
    rows (with command_parameters/response/additional_metadata decoded
    from JSON text into nested objects, not left as double-encoded
    strings) only with --include-raw-hardware-log.
    """
    if not telemetry_available:
        return {"available": False, "reason": reason, "hardware_failure_count": None, "unique_error_types": []}

    failures = [row for row in rows if not row.get("success")]
    unique_error_types = sorted({row["error_type"] for row in failures if row.get("error_type")})

    section = {
        "available": True,
        "row_count": len(rows),
        "hardware_failure_count": len(failures),
        "unique_error_types": unique_error_types,
        "full_rows_included": include_full,
        "rows": None,
    }
    if include_full:
        decoded_rows = []
        for row in rows:
            decoded = dict(row)
            for field in ("command_parameters", "response", "additional_metadata"):
                decoded[field] = _decode_json_field(decoded.get(field))
            decoded_rows.append(decoded)
        section["rows"] = decoded_rows
    return section


def _run_ref(row: dict) -> dict:
    return {
        "run_id": row.get("run_id"), "test_type": row.get("test_type"),
        "stop_reason": row.get("stop_reason"), "result": row.get("result"),
    }


def _build_related_runs(*, parent_run: dict, child_runs: list) -> dict:
    """
    Cycle/phase forensic linkage (see data/storage.py's `parent_run_id`
    column and test_control/cycle_sequence.py) -- lets a reader/AI walk
    from a CycleSequence phase row to its umbrella cycle_battery row, or
    from a cycle_battery row to its charge/discharge phase rows, WITHOUT a
    second export_run.py invocation or a fragile group_name/position/time-
    proximity heuristic. Both lists are empty/null for a run that has no
    cycle relationship at all (every non-CycleSequence run_id).
    """
    return {
        "parent": _run_ref(parent_run) if parent_run else None,
        "children": [_run_ref(row) for row in child_runs],
    }


def _build_metadata(*, run_id: str, run: dict, telemetry_available: bool,
                     telemetry_unavailable_reason, flags: dict, sections_included: list) -> dict:
    return {
        "export_version": EXPORT_VERSION,
        "exported_at": datetime.now().isoformat(),
        "run_id": run_id,
        "telemetry_db": run.get("telemetry_db"),
        "telemetry_available": telemetry_available,
        "telemetry_unavailable_reason": telemetry_unavailable_reason,
        "generator": "scripts/export_run.py",
        "flags": flags,
        "sections_included": sections_included,
        "description": DESCRIPTION,
    }


# -----------------------------------------------------------------------
# Orchestration
# -----------------------------------------------------------------------

def build_export(run_id: str, *, settings=Settings, summary_only: bool = False,
                  include_measurements: bool = False, include_raw_hardware_log: bool = False) -> dict:
    """
    Assemble the complete forensic export dict for `run_id`. Raises
    ExportError only if run_id itself cannot be found in the index
    database -- a run that IS found but has unreachable telemetry is NOT
    an error: every index-database-backed section is still exported in
    full, and every telemetry-dependent section is marked unavailable
    with an explicit reason (see module docstring).
    """
    storage, error = DataStorage.open_for_forensic_export(settings, run_id)
    if storage is None:
        raise ExportError(error)

    try:
        run = storage.get_run_summary(run_id)
        telemetry_available = storage._db is not None
        unavailable_reason = storage.telemetry_unavailable_reason
        station_state_rows = storage.get_station_state_for_run(run_id)
        child_runs = storage.get_child_run_summaries(run_id)
        parent_run = storage.get_run_summary(run["parent_run_id"]) if run and run.get("parent_run_id") else None
        if telemetry_available:
            event_rows = storage.get_recent_events(run_id=run_id, limit=None)
            measurement_rows = storage.get_measurements(run_id=run_id)
            raw_rows = storage.get_raw_hardware_log(run_id)
        else:
            event_rows, measurement_rows, raw_rows = [], [], []
    finally:
        storage.close()

    safety_section = (
        _build_safety_section(event_rows) if telemetry_available
        else _unavailable_safety_section(unavailable_reason)
    )
    forensic_findings = _build_forensic_findings(safety_section["fault_timeline"])
    incident_summary = _build_incident_summary(
        run, station_state_rows, safety_section, event_rows, telemetry_available,
    )
    related_runs = _build_related_runs(parent_run=parent_run, child_runs=child_runs)

    if summary_only:
        timeline, critical_events, execution_state, event_log = [], [], [], []
    else:
        timeline = _build_timeline(event_rows, station_state_rows)
        critical_events = _build_critical_events(timeline)
        execution_state = station_state_rows
        event_log = _build_event_log_section(event_rows)

    measurements = _build_measurements_section(measurement_rows, include_measurements, telemetry_available, unavailable_reason)
    raw_hardware_log = _build_raw_hardware_log_section(raw_rows, include_raw_hardware_log, telemetry_available, unavailable_reason)

    sections_included = ["metadata", "incident_summary", "safety", "forensic_findings", "run_summary", "related_runs"]
    if not summary_only:
        sections_included += ["timeline", "critical_events", "execution_state", "event_log"]
    if include_measurements:
        sections_included.append("measurements")
    if include_raw_hardware_log:
        sections_included.append("raw_hardware_log")

    metadata = _build_metadata(
        run_id=run_id, run=run, telemetry_available=telemetry_available,
        telemetry_unavailable_reason=unavailable_reason,
        flags={
            "summary_only": summary_only, "include_measurements": include_measurements,
            "include_raw_hardware_log": include_raw_hardware_log,
        },
        sections_included=sections_included,
    )

    # Key order matches the approved top-level order exactly -- json.dump()
    # preserves dict insertion order; NEVER pass sort_keys=True downstream,
    # that would alphabetize and destroy this deliberate ordering.
    # `related_runs` is a later, additive field (cycle/phase linkage via
    # parent_run_id) -- placed immediately after `run_summary` since it's
    # directly about that section, not part of the original approved order.
    return {
        "metadata": metadata,
        "incident_summary": incident_summary,
        "timeline": timeline,
        "safety": safety_section,
        "forensic_findings": forensic_findings,
        "critical_events": critical_events,
        "run_summary": run,
        "related_runs": related_runs,
        "execution_state": execution_state,
        "event_log": event_log,
        "measurements": measurements,
        "raw_hardware_log": raw_hardware_log,
    }


def _resolve_output_path(output_path, run_id: str, use_gzip: bool) -> str:
    if output_path is None:
        base = f"{run_id}.json"
    else:
        base = output_path[:-3] if output_path.endswith(".gz") else output_path
        if not base.endswith(".json"):
            base = f"{base}.json"
    return f"{base}.gz" if use_gzip else base


def write_export(export: dict, *, run_id: str, output_path: str = None, gzip_flag: bool = None,
                  size_threshold_bytes: int = DEFAULT_GZIP_THRESHOLD_BYTES) -> str:
    """
    Serialize `export` to pretty-printed JSON and write it to disk.

    `gzip_flag=True`/`False` forces the choice regardless of size;
    `gzip_flag=None` (default) auto-switches to `.json.gz` only if the
    serialized payload exceeds `size_threshold_bytes` -- most AI upload
    surfaces accept plain JSON directly but won't necessarily decompress
    `.gz` automatically, so gzip is never the silent default. Returns the
    actual path written.
    """
    payload = json.dumps(export, indent=2, sort_keys=False, default=str)
    payload_bytes = payload.encode("utf-8")
    use_gzip = gzip_flag if gzip_flag is not None else len(payload_bytes) > size_threshold_bytes

    path = _resolve_output_path(output_path, run_id, use_gzip)
    if use_gzip:
        with gzip.open(path, "wt", encoding="utf-8") as f:
            f.write(payload)
    else:
        with open(path, "w", encoding="utf-8") as f:
            f.write(payload)
    return path


_HELP_EPILOG = f"""\
examples:
  python scripts/export_run.py RACK01-00000001
      Full default export -> RACK01-00000001.json (run_summary, incident_summary,
      timeline, safety, forensic_findings, critical_events, execution_state,
      event_log, plus measurement/raw-hardware-log summaries -- not full rows).

  python scripts/export_run.py RACK01-00000001 --summary-only
      Smallest/fastest export -- metadata, incident_summary, safety,
      forensic_findings, run_summary only. Good for triaging many runs quickly.

  python scripts/export_run.py RACK01-00000001 --include-measurements --include-raw-hardware-log
      Full export, including every raw measurement and raw_hardware_log row
      (not just their summaries) -- for a deep-dive investigation of one run.

  python scripts/export_run.py RACK01-00000001 --output findings.json
      Write to an explicit path instead of the default <run_id>.json.

gzip:
  By default the output is plain, uncompressed JSON -- most AI upload
  surfaces (claude.ai, Copilot Chat) accept plain JSON directly and won't
  necessarily decompress .gz automatically. It is automatically switched to
  .json.gz only if the serialized payload exceeds {DEFAULT_GZIP_THRESHOLD_BYTES // (1024 * 1024)} MB
  (see --include-measurements/--include-raw-hardware-log above, which are
  the two flags most likely to cross that threshold). --gzip/--no-gzip
  override this in either direction regardless of size.

exit codes:
  0  export written successfully (telemetry may still be unavailable for a
     pre-migration run -- see the printed [WARNING] line and
     metadata.telemetry_unavailable_reason in the artifact itself)
  1  run_id not found in the index database (nothing was written)
"""


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Export a complete, self-contained forensic record for one run_id -- "
                     "a single JSON artifact meant to be uploaded directly to an AI system "
                     "(Claude, Copilot, or a future forensic tool) for incident investigation.",
        epilog=_HELP_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("run_id", help="e.g. RACK01-00000001 (see run_summary.run_id / incident_summary.run_id)")
    parser.add_argument("--output", default=None, help="Output file path (default: <run_id>.json[.gz])")
    parser.add_argument("--summary-only", action="store_true",
                         help="metadata + incident_summary + safety + forensic_findings + run_summary only "
                              "(omits timeline/critical_events/execution_state/event_log entirely)")
    parser.add_argument("--include-measurements", action="store_true",
                         help="embed full measurement rows (default: row_count + per-channel "
                              "statistics + first/last sample + a bounded sample only)")
    parser.add_argument("--include-raw-hardware-log", action="store_true",
                         help="embed full raw_hardware_log rows, JSON-decoded (default: "
                              "hardware_failure_count + unique_error_types only)")
    gzip_group = parser.add_mutually_exclusive_group()
    gzip_group.add_argument("--gzip", action="store_true",
                             help="always write .json.gz, regardless of size")
    gzip_group.add_argument("--no-gzip", action="store_true",
                             help="always write plain .json, regardless of size "
                                  "(default without either flag: auto-gzip above "
                                  f"{DEFAULT_GZIP_THRESHOLD_BYTES // (1024 * 1024)} MB)")
    args = parser.parse_args(argv)

    gzip_flag = True if args.gzip else (False if args.no_gzip else None)

    try:
        export = build_export(
            args.run_id, summary_only=args.summary_only,
            include_measurements=args.include_measurements,
            include_raw_hardware_log=args.include_raw_hardware_log,
        )
    except ExportError as e:
        print(f"[FAIL] {e}")
        return 1

    path = write_export(export, run_id=args.run_id, output_path=args.output, gzip_flag=gzip_flag)
    print(f"Exported {args.run_id} -> {path}")
    if not export["metadata"]["telemetry_available"]:
        print(f"[WARNING] telemetry unavailable: {export['metadata']['telemetry_unavailable_reason']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
